name: Matrix Demo
on: 
  push
jobs:
  Build:
    continue-on-error: true
    strategy:
      matrix:
        node-v: [12,18,20] 
        os-v: [ubuntu-latest, windows-latest]
      include:
        - node-v: 16
        - os-v: ubuntu-latest
      exclude:
        - node-v: 12
        - os-v: windows-latest
    runs-on: ${{ matrix.os-v }}
    steps:
          - name: Get Code
            uses: actions/checkout@v4
          - name: Install NodeJS
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-v }}
          - name: Install Dependencies
            run: npm ci  
          - name: Build Project
            run: npm run build    