name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact file
        required: false
        default: dist
        type: string
    secrets:
      user-name:
        required: true
    outputs:
      result:
        description: The result of deploying files
        value: ${{ jobs.reuse-deploy.outputs.outcome }}
jobs:
  reuse-deploy:
    env:
          USER_NAME: 'Dog'
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Check user-name
        run: echo "Checking user-name"
      - name: List  
        run: echo ${{ env.USER_NAME }}
      - name: Deploy Files
        run:  echo 'Deploying ... ...'
      - name: Set Deploying result
        id: set-result
        run: echo "step-result= success" >> $GITHUB_OUTPUT