name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact file
        required: false
        default: dist
        type: string
    secrets:
      user-name:
        required: true
jobs:
  reuse-deploy:
    env:
          USER_NAME: 'Dog'
    runs-on: ubuntu-latest
    steps:
      - name: Get Files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Check user-name
        run: echo "Checking user-name"
      - name: List  
        run: echo ${{ env.USER_NAME }}
      - name: Deploy Files
        run:  echo 'Deploying ... ...'