name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact file
        required: false
        default: dist
        type: string
    secrets:
      user-name:
        required: true
jobs:
  reuse-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: List secret
        if: ${{ secrets.user-name == 'mihai' }}
        run: echo 'Found user-name  mihai '
      - name: Deploy Files
        run:  echo 'Deploying ... ...'